# Generated by Django 5.1.5 on 2025-02-11 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='Event_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='website_app.event')),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserEvents',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
