# Generated by Django 5.1.5 on 2025-02-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_organization_invite_code_userorganization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventgroups',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventgroups',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_groups', to='website_app.event'),
        ),
        migrations.AlterField(
            model_name='eventgroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_events', to='website_app.group'),
        ),
        migrations.AlterModelTable(
            name='eventgroups',
            table=None,
        ),
    ]
