# Generated by Django 5.1.5 on 2025-02-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_alter_eventgroups_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroups',
            name='event',
            field=models.ForeignKey(db_column='Event_ID', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='website_app.event'),
        ),
        migrations.AlterField(
            model_name='eventgroups',
            name='group',
            field=models.ForeignKey(db_column='Group_ID', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website_app.group'),
        ),
        migrations.AlterUniqueTogether(
            name='eventgroups',
            unique_together={('group', 'event')},
        ),
        migrations.AlterModelTable(
            name='eventgroups',
            table='EventGroups',
        ),
    ]
