# Generated by Django 5.1.5 on 2025-05-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_within_radius', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='website_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventCheckIn',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
