# Generated by Django 5.1.5 on 2025-05-07 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_alter_event_location_alter_role_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
