# Generated by Django 5.1.5 on 2025-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
