# Generated by Django 5.1.5 on 2025-05-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_group_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='color',
        ),
    ]
