# Generated by Django 5.1.5 on 2025-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0014_remove_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#6666ff', max_length=7),
        ),
    ]
