# Generated by Django 5.1.5 on 2025-05-11 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0016_eventattendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_substitutions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='website_app.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_substitutions', to='website_app.group')),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to=settings.AUTH_USER_MODEL)),
                ('substitute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventSubstitution',
                'unique_together': {('event', 'original_user', 'group')},
            },
        ),
    ]
