# Generated by Django 5.1.5 on 2025-05-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0018_substitutionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsubstitution',
            unique_together={('event', 'original_user')},
        ),
        migrations.AlterUniqueTogether(
            name='substitutionrequest',
            unique_together={('event', 'requesting_user', 'target_user')},
        ),
        migrations.RemoveField(
            model_name='eventsubstitution',
            name='group',
        ),
        migrations.RemoveField(
            model_name='substitutionrequest',
            name='group',
        ),
    ]
