# Generated by Django 5.1.5 on 2025-05-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0024_remove_chat_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='chat',
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatParticipant',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
